"""Initial migration

Revision ID: 2018d5d881db
Revises: 
Create Date: 2026-08-23 01:34:31.542125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2018d5d881db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('api_key_prefix', sa.String(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_api_keys_api_key_prefix'), 'project_api_keys', ['api_key_prefix'], unique=False)
    op.create_index(op.f('ix_project_api_keys_id'), 'project_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_project_api_keys_project_name'), 'project_api_keys', ['project_name'], unique=False)
    op.create_table('provider_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supported_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_metadata_id'), 'provider_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_provider_metadata_name'), 'provider_metadata', ['name'], unique=True)
    op.create_table('provider_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('current_quota_usage', sa.Integer(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_provider_state_id'), 'provider_state', ['id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('request_latency_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_metrics_id'), 'usage_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_usage_metrics_project_id'), 'usage_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_metrics_timestamp'), 'usage_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_metrics_timestamp'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_project_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_id'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_provider_state_id'), table_name='provider_state')
    op.drop_table('provider_state')
    op.drop_index(op.f('ix_provider_metadata_name'), table_name='provider_metadata')
    op.drop_index(op.f('ix_provider_metadata_id'), table_name='provider_metadata')
    op.drop_table('provider_metadata')
    op.drop_index(op.f('ix_project_api_keys_project_name'), table_name='project_api_keys')
    op.drop_index(op.f('ix_project_api_keys_id'), table_name='project_api_keys')
    op.drop_index(op.f('ix_project_api_keys_api_key_prefix'), table_name='project_api_keys')
    op.drop_table('project_api_keys')
    # ### end Alembic commands ###
