"""add_quota_fields_to_provider_state

Revision ID: bae047f1496d
Revises: 2018d5d881db
Create Date: 2026-08-30 01:04:25.347818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae047f1496d'
down_revision: Union[str, Sequence[str], None] = '2018d5d881db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_state', sa.Column('availability', sa.String(), nullable=True))
    op.add_column('provider_state', sa.Column('quota_confidence', sa.String(), nullable=True))
    op.add_column('provider_state', sa.Column('request_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('provider_state', sa.Column('token_usage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('provider_state', sa.Column('rate_limit_events', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('provider_state', sa.Column('last_quota_failure', sa.DateTime(), nullable=True))
    op.add_column('provider_state', sa.Column('cooldown_until', sa.DateTime(), nullable=True))
    op.add_column('provider_state', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
    
    # Set default values for existing rows
    op.execute("UPDATE provider_state SET availability = 'available' WHERE availability IS NULL")
    op.execute("UPDATE provider_state SET quota_confidence = 'unknown' WHERE quota_confidence IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_state', 'consecutive_failures')
    op.drop_column('provider_state', 'cooldown_until')
    op.drop_column('provider_state', 'last_quota_failure')
    op.drop_column('provider_state', 'rate_limit_events')
    op.drop_column('provider_state', 'token_usage')
    op.drop_column('provider_state', 'request_count')
    op.drop_column('provider_state', 'quota_confidence')
    op.drop_column('provider_state', 'availability')
    # ### end Alembic commands ###
